### ISSUE TITLE
ABSPATH modules/hooks.php

### ISSUE THREAD

**Issue by spka** [getastra/wp-security-hardening#39]
Hey, quick question. I use a custom wordpress folder. The modules/hooks.php starts the plugin with:

```
<?php
require_once(dirname(__FILE__, 3) . "/../../wp-includes/pluggable.php");
require_once(dirname(__FILE__, 3) . "/../../wp-load.php");
if (!defined('ABSPATH')) exit ('Peekaboo!');
```
This creates an error if wordpress isn't in the default folder. Is that on purpose? This code fixes it:

```
if (!defined('ABSPATH')) exit ('Peekaboo!');
require_once(ABSPATH."/wp-includes/pluggable.php");
require_once(ABSPATH."/wp-load.php");`
```

If needed i can create a pull request 😄

**Comment by anandakrishna** [comment]
Hey @spka! Definitely an oversight by the dev. A PR would be much appreciated :D

**Comment by anandakrishna** [comment]
Thank you for the PD @spka . A new version has been released: https://github.com/getastra/wp-security-hardening/releases/tag/1.2.3
