### ISSUE TITLE
Plugin breaks WP Cli

### ISSUE THREAD

**Issue by adamtomat** [getastra/wp-security-hardening#49]
### Describe the bug
With the plugin installed and activated, when you use wp-cli this plugin throws the following error:

```
Undefined array key "QUERY_STRING" in wp-security-hardening/modules/hooks.php line 201
```

This is the offending line:

https://github.com/getastra/wp-security-hardening/blob/master/modules/hooks.php#L201

### To Reproduce
1. Install WordPress with this plugin installed
2. Run a wp-cli command, for example:`$ wp option get home`

### Expected behavior
It should show the home url you have set for the site.

### Actual behavior
It errors with:

```
Undefined array key "QUERY_STRING" in wp-security-hardening/modules/hooks.php line 201
```
### Suggested fix
Add a check to make sure this variable exists in `$_SERVER` before accessing it.

#### Desktop (please complete the following information):
 - OS: macOS Monterey
 - Version: 12.4

#### Used versions
* WordPress version: 6.0.1
* WP Hardening version: 1.2.5
* WP Cli version: 2.6.0

### Additional context
This also causes an issue when serving WordPress with `php -S 127.0.0.1:8080` as that also doesn't set the `QUERY_STRING` variable on `$_SERVER`.

**Comment by adamtomat** [comment]
As this has been merged in, is it possible to get a tagged release, please? We bring this plugin in via composer and currently cannot benefit from this as it's not tagged yet

**Comment by anandakrishna** [comment]
Sure thing, @adamtomat. It should be available on the directory now. v1.2.6.
